name: Credo

on: push

jobs:
  Credo:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.2' # Define the elixir version [required]
          otp-version: '26.0' # Define the OTP version [required]

      - name: Cache Deps & Build
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-mix-credo-${{ hashFiles('**/mix.lock') }}
          path: |
            deps
            _build
          restore-keys: |
            ${{ runner.os }}-mix-credo-

      - name: Install Dependencies
        run: mix deps.get

      - name: Compile Project
        run: mix compile

      - name: Run Credo
        run: mix credo
